"""Rebuild the manually reviewed Pass 4 claim ledger from timed caption evidence.

These are researcher paraphrases, not automated extraction or verified gameplay facts.
"""

import csv
import json
from pathlib import Path

ROOT = Path(__file__).parent
VIDEO = {r["video_id"]: r for r in csv.DictReader((ROOT / "pass01_public_index.csv").open())}

# id, video, start seconds, end seconds, topic, paraphrased claim, class,
# scope/condition, transcript confidence, visual dependency, review note
CLAIMS = [
 ("P4-001","JM50b3IU6-c",47,77,"composition/space","A split composition can form two or sometimes three cores, creating pressure from distinct map areas rather than moving as a five-player rush unit.","definition","Split composition, 2023 example","high","medium","General explanation; visual only needed for exact map geometry."),
 ("P4-002","JM50b3IU6-c",117,140,"composition/vocabulary","He calls the larger or tank-containing group the core and the smaller or tankless group the off angle, while acknowledging the terminology is partly conventional.","definition","His usage in this video","high","low","Preserve this local vocabulary rather than assume universal terms."),
 ("P4-003","JM50b3IU6-c",540,604,"space/tempo","When one split core is rushed, it should retreat while the other pressures the enemy's trailing support and forces cooldowns, kills, or objective value; the two cores push and pull simultaneously.","conditional_rule","Split composition facing a rush","high","high","Spoken mechanism clear; actual flank geometry and results require video review."),
 ("P4-004","JM50b3IU6-c",1120,1190,"space/tempo","A pressured off angle has already contributed by drawing resources; trying to push both cores at once can throw away the advantage. The pressured core should keep attention while surviving.","conditional_rule","Toronto–Washington side-lane example","high","high","He narrates a specific fight; do not treat outcome as independently verified."),
 ("P4-005","c92ESPjlveI",58,90,"turns","A turn is a period when a team spends cooldowns or takes space for proactive value; taking a first turn, a second turn, and a simultaneous neutralizing turn are distinct choices.","definition","Brawl and dive examples; poke acknowledged as less obvious","high","low","Explicit definition; transcript has automatic-caption errors for hero names elsewhere."),
 ("P4-006","c92ESPjlveI",125,228,"turns/space","Simultaneous neutralization tends to preserve the current map state, while sequential turns seek to change it. A team attacking a strong defensive setup cannot rely on neutralization alone to gain space.","conditional_rule","Dive into entrenched defense","high","medium","Generalization as expressed by speaker, not proof across all maps."),
 ("P4-007","c92ESPjlveI",395,445,"turns/objective","A space-poor dive team can pressure cart or set DPS angles to make the opposing Winston spend his first turn, creating a later second-turn opportunity.","mechanism","Dive mirror example","high","high","Exact positioning depends on the on-screen demonstration."),
 ("P4-008","c92ESPjlveI",550,625,"turns/setup","Soft dives can extend one's own time in while baiting enemy cooldown cycles; after the opposing Winston leaves, the team can use its second turn with backline and DPS aggression.","conditional_rule","Illustrated dive mirror","medium","high","Specific execution sequence should be visually audited."),
 ("P4-009","z9n-JNB52rk",39,84,"space/positioning","A backline that follows its tank tightly around a corner is easier for the opposing tank to reach than a backline offset from that corner.","mechanism","Corner swing and tank–backline trade","high","high","Requires visual review for geometry and example validity."),
 ("P4-010","z9n-JNB52rk",135,195,"composition/space","He frames many Overwatch 2 fights as tank–backline reach and trade problems and says a team may engage or bait that interaction; these are broad explanatory simplifications, not strict composition taxonomy.","framework","Overwatch 2; explicit broad simplification","high","medium","Potential tension with older brawl/dive/poke vocabulary, not a proved contradiction."),
 ("P4-011","z9n-JNB52rk",457,521,"space/positioning","A team going first around a corner can still plan to kite in the midfight; its backline needs an offset position and a window, such as an opponent's key cooldown being spent.","conditional_rule","Orisa mirror example","medium","high","Map and cooldown names in ASR are unreliable; inspect original video."),
 ("P4-012","pMPwEwNEiQA",115,178,"attention/player","After a successful Genji engage, the player should recheck enemy threats before chasing another kill; tunnel vision turns a favorable trade into a needless coin flip.","conditional_rule","Genji review","high","high","Specific fight result is the speaker's interpretation."),
 ("P4-013","pMPwEwNEiQA",490,535,"attention/player","For Genji, tracking who is looking at him and when pressure shifts matters more than merely minimizing damage taken.","mechanism","Illustrated Genji play","medium","high","Strong phrasing depends on replay scene; preserve as his heuristic."),
 ("P4-014","K6Ayz-NHVe4",90,165,"turns","He defines going first as choosing the engage and going second or baiting as allowing the opponent to commit before responding; hero and meta affect how those actions look.","definition","2024 analysis; his stated personal usage","high","low","Compare later refinements of first/second terminology."),
 ("P4-015","K6Ayz-NHVe4",400,460,"space/setup","An effective bait setup preserves the ability to punish an incoming engage; simply kiting without ever standing ground to punish it misses the purpose.","conditional_rule","Illustrated Korean team defense","high","high","Video needed to test whether the setup actually prevented the engage."),
 ("P4-016","MYW1ztAeDQc",55,115,"dive/setup","The expected outcome of a mirrored Winston–Tracer dive depends heavily on the quality of each dive's staging, rather than a fixed rule that the backline always lives or dies.","framework","Dive mirror hypothetical","high","medium","Speaker recognizes player skill and ultimates as additional factors."),
 ("P4-017","MYW1ztAeDQc",245,342,"dive/prevention","Against a well-staged dive, reviewing only defensive cooldown execution is often too late; instead, prevent the Tracer angle or Winston jump from becoming favorable before walking up.","conditional_rule","Ana–Brigitte retake example","high","high","The emphatic 'impossible to live' rhetoric is conditional on a genuinely good dive."),
 ("P4-018","MYW1ztAeDQc",600,700,"dive/retake","A wide retake route can clear or displace the dive setup, presenting the enemy Winston with a poor long-distance dive or a concession of space.","mechanism","Falcons retake example","medium","high","Requires map and POV review before elevating to a general rule."),
 ("P4-019","E1bYy6OE_OQ",45,99,"information/setup","Before a good setup, teammates should maximize safe sight of the enemy; he distinguishes broad team sight from scouting a specific player.","definition","2025 Geekay analysis","high","medium","His term 'sight maxing' is local vocabulary, not a validated metric."),
 ("P4-020","E1bYy6OE_OQ",120,200,"information/setup","Poking far forward between fights can reveal the enemy's walk-up, after which a team can withdraw behind a corner while retaining information and denying the same view to its opponent.","mechanism","Geekay versus Nightmare illustration","high","high","Visual inspection needed to verify visibility for each POV."),
 ("P4-021","LpxT2dykNK0",40,100,"staging/space","The pre-fight staging phase is a contest over how each team shapes the fight; conceding angles and retreating only after the enemy has finished setting up can lose before the nominal engage.","framework","Korean versus Western example","medium","high","Avoid turning regional rhetoric into a universal empirical claim."),
 ("P4-022","1OvQ5PAK0w0",30,80,"review/attention","Replay analysis should reconstruct what players could know and were prioritizing at the moment, rather than explain a death solely with hindsight.","method","2025 match review","high","medium","Ascribes possible mental states; verify through player POV where possible."),
 ("P4-023","1OvQ5PAK0w0",110,190,"review/attention","A postgame list of correct actions can be less useful than identifying the in-game attention process that prevented known actions from being executed under limited mental bandwidth.","method","Coaching and match review","high","low","Distinct from denying value of tactical knowledge."),
 ("P4-024","1UNctVbRS3M",25,90,"composition/setup","Low-damage double-flex DPS setups cannot rely as much on forcing tank cooldowns or long-range picks; they depend more on pathing, scouting, and avoiding head-on contests.","conditional_rule","Specific double-flex DPS composition discussion","medium","high","Patch and composition context must be checked before generalizing."),
 ("P4-025","1UNctVbRS3M",90,175,"cooldowns/tempo","A DPS may yield an angle to an opponent's clearing attempt, preserving own resources; the opponent's spent movement and subsequent retreat become a window to re-enter.","mechanism","Specific Genji/D.Va illustration","medium","high","Counterplay depends on exact paths and cooldown state."),
 ("P4-026","aHwWbiUE4KQ",0,95,"ultimate_economy","Ultimate economy still exists, but he argues it generally carries less explanatory weight in Overwatch 2 than in Overwatch 1; he explicitly exempts some D.Va, Zarya, and Symmetra compositions.","qualified_thesis","2026-01 analysis; composition and meta dependent","high","low","Title is deliberately stronger than the actual spoken claim."),
 ("P4-027","aHwWbiUE4KQ",100,250,"ultimate_economy","More individual playmaking, splits, and messy trades can let a team win despite spending or facing an apparent ultimate deficit.","mechanism","Overwatch 2 versus Overwatch 1 argument","medium","high","Match outcome examples have not been independently checked."),
 ("P4-028","aHwWbiUE4KQ",265,400,"ultimate_economy/space","Spacing the backline while a sturdier front line shows can draw an enemy ultimate and permit a kite, making the opponent's stored ultimate less decisive.","mechanism","Specific bait example; more mobile OW2 context","medium","high","Visual review required for the actual spacing and timing."),
 ("P4-029","aHwWbiUE4KQ",440,555,"ultimate_economy/objective","Winning a fight can generate later ultimate charge and next-fight setup; losing a fight creates a retake burden, so counting only ultimates spent omits these state changes.","mechanism","Meta dependent; his third reason","high","medium","Numerical charge examples should be checked visually."),
 ("P4-030","Hl-nV1aF1yE",55,160,"space/tempo","When a direct push through a prepared Sig/Bastion and Mei defense is unworkable, backing out early can hide a new route and create a later push opportunity.","conditional_rule","Specific map and composition situation","high","high","Do not generalize as retreating whenever pushing is hard."),
 ("P4-031","Hl-nV1aF1yE",190,310,"space/tempo","Early voluntary withdrawal while cooldowns and distance remain differs from backing up after poke has forced a retreat; the latter can allow pursuit and further loss of space.","distinction","Explicit response to possible tension with prior 'Lock Eyes and Fight' video","high","high","Speaker himself flags and reconciles the apparent contradiction."),
 ("P4-032","Hl-nV1aF1yE",345,405,"space/tempo","After spending an unsuccessful first turn, a team can retreat before the opponent closes, retain room to act, and regain the initiative for a later turn.","mechanism","Twisted Minds example","medium","high","Outcome and spacing need visual verification."),
 ("P4-033","KlcWDgdXrZk",0,98,"turns/vocabulary","First and second are useful descriptions of timing but poor instructions on their own; playing second requires flexible coverage of possible opponent decisions.","framework","2026 Falcons–Crazy Raccoon match","high","high","Refines the 2023–2024 vocabulary without rejecting it."),
 ("P4-034","KlcWDgdXrZk",135,365,"turns/opponent_model","A team seeking to play second may intentionally offer a cooldown trade or punishable position to induce a predictable opponent commitment, then arrange a counter-engage.","mechanism","Falcons examples","high","high","Speaker also shows this can fail; see P4-035."),
 ("P4-035","KlcWDgdXrZk",635,735,"turns/counterplay","The first-moving team can accept such bait if it responds quickly and coherently; a second-moving team that spends cooldowns to bait and then merely mirrors the same engage risks losing the cooldown trade.","counterexample","Falcons–Crazy Raccoon later fight","high","high","Prevents treating P4-034 as an always-win rule."),
 ("P4-036","GKkzCd9cvUg",110,180,"ultimate_economy","In the later follow-up he maintains that spending multiple support ultimates to win can be acceptable; the reviewed failure was spending them while losing and without a viable post-fight setup.","clarification","2026-04 follow-up to 2026-01 thesis","high","high","Explicitly distinguishes ult spending from failure to win a fight."),
 ("P4-037","GKkzCd9cvUg",230,350,"ultimate_economy/positioning","In the reviewed Zenyatta–Brigitte fight, he prefers a wide swing and kiting the opposing response rather than committing into it with both support ultimates.","case_judgment","Specific match, may depend on cooldown tracking","medium","high","He acknowledges uncertainty about exact ult tracking."),
 ("P4-038","GKkzCd9cvUg",390,475,"ultimate_economy/setup","A point flip is insufficient if the team clusters on point and lacks angles or a pinch for the next touch; the quality of the resulting setup matters more than the count of ultimates spent.","case_judgment","Specific post-ultimate retake","high","high","Visually validate positioning and outcome."),
 ("P4-039","KLwLiiYYewQ",0,51,"information/space","Poking past a choke before backing up can locate the opponent and preserve initiative; simply holding the choke can permit the enemy to arrange its own play.","conditional_rule","One short 2026 commentary clip","medium","high","Short clip; not enough context for a universal rule."),
 ("P4-040","_pv_dhja-4w",135,305,"learning/method","For players below the highest level, he recommends deliberate observation of real games over relying on first-principles mental simulation of an extremely complex game.","method","2026-09 learning advice; explicitly qualified for top experts","high","low","Rhetorical ranking advice, not a measured learning experiment."),
 ("P4-041","_pv_dhja-4w",310,555,"learning/method","He recommends writing a detailed record of a pro replay to expose unnoticed events and patterns, then comparing a closely matched own replay to identify differences.","method","Serious, time-intensive practice proposal","high","low","He admits the three-step scheme was improvised; do not invent a missing step."),
 ("P4-042","_pv_dhja-4w",620,690,"learning/evidence","When testing a tactical disagreement, seek several closely comparable real examples and check for confounds rather than relying only on hypothetical arguments.","method","Non-expert learning and team discussion","high","low","Consistent with P4-022 but a distinct claim about evidence."),
]

def clock(seconds):
    return f"{seconds//3600:02d}:{seconds//60%60:02d}:{seconds%60:02d}"

def main():
    seen = set()
    rows = []
    for id_, video_id, start, end, topic, claim, claim_class, scope, confidence, visual, note in CLAIMS:
        assert id_ not in seen and start < end
        seen.add(id_)
        meta = VIDEO[video_id]
        rows.append(dict(claim_id=id_, video_id=video_id, video_title=meta["title"], upload_date=meta["upload_date"], start=clock(start), end=clock(end), start_seconds=start, end_seconds=end, url=f"https://www.youtube.com/watch?v={video_id}&t={start}s", topic=topic, claim=claim, claim_class=claim_class, scope=scope, evidence_type="automatic_caption_speaker_paraphrase", transcript_confidence=confidence, visual_dependency=visual, review_note=note, gameplay_verified=False, status="provisional"))
    with (ROOT / "pass04_claims.jsonl").open("w") as f:
        for row in rows: f.write(json.dumps(row,ensure_ascii=False)+"\n")
    with (ROOT / "pass04_claims.csv").open("w",newline="") as f:
        w=csv.DictWriter(f,fieldnames=rows[0].keys()); w.writeheader();w.writerows(rows)
    print(f"Wrote {len(rows)} claims from {len(set(r['video_id'] for r in rows))} videos")

if __name__ == "__main__": main()
