"""Rebuild the manually reviewed Pass 4 claim ledger from timed caption evidence.

These are researcher paraphrases, not automated extraction or verified gameplay facts.
"""

import csv
import json
from pathlib import Path

ROOT = Path(__file__).parent
VIDEO = {r["video_id"]: r for r in csv.DictReader((ROOT / "pass01_public_index.csv").open())}

# id, video, start seconds, end seconds, topic, paraphrased claim, class,
# scope/condition, transcript confidence, visual dependency, review note
CLAIMS = [
 ("P4-001","JM50b3IU6-c",47,77,"composition/space","A split composition can form two or sometimes three cores, creating pressure from distinct map areas rather than moving as a five-player rush unit.","definition","Split composition, 2023 example","high","medium","General explanation; visual only needed for exact map geometry."),
 ("P4-002","JM50b3IU6-c",117,140,"composition/vocabulary","He calls the larger or tank-containing group the core and the smaller or tankless group the off angle, while acknowledging the terminology is partly conventional.","definition","His usage in this video","high","low","Preserve this local vocabulary rather than assume universal terms."),
 ("P4-003","JM50b3IU6-c",540,604,"space/tempo","When one split core is rushed, it should retreat while the other pressures the enemy's trailing support and forces cooldowns, kills, or objective value; the two cores push and pull simultaneously.","conditional_rule","Split composition facing a rush","high","high","Spoken mechanism clear; actual flank geometry and results require video review."),
 ("P4-004","JM50b3IU6-c",1120,1190,"space/tempo","A pressured off angle has already contributed by drawing resources; trying to push both cores at once can throw away the advantage. The pressured core should keep attention while surviving.","conditional_rule","Toronto–Washington side-lane example","high","high","He narrates a specific fight; do not treat outcome as independently verified."),
 ("P4-005","c92ESPjlveI",58,90,"turns","A turn is a period when a team spends cooldowns or takes space for proactive value; taking a first turn, a second turn, and a simultaneous neutralizing turn are distinct choices.","definition","Brawl and dive examples; poke acknowledged as less obvious","high","low","Explicit definition; transcript has automatic-caption errors for hero names elsewhere."),
 ("P4-006","c92ESPjlveI",125,228,"turns/space","Simultaneous neutralization tends to preserve the current map state, while sequential turns seek to change it. A team attacking a strong defensive setup cannot rely on neutralization alone to gain space.","conditional_rule","Dive into entrenched defense","high","medium","Generalization as expressed by speaker, not proof across all maps."),
 ("P4-007","c92ESPjlveI",395,445,"turns/objective","A space-poor dive team can pressure cart or set DPS angles to make the opposing Winston spend his first turn, creating a later second-turn opportunity.","mechanism","Dive mirror example","high","high","Exact positioning depends on the on-screen demonstration."),
 ("P4-008","c92ESPjlveI",550,625,"turns/setup","Soft dives can extend one's own time in while baiting enemy cooldown cycles; after the opposing Winston leaves, the team can use its second turn with backline and DPS aggression.","conditional_rule","Illustrated dive mirror","medium","high","Specific execution sequence should be visually audited."),
 ("P4-009","z9n-JNB52rk",39,84,"space/positioning","A backline that follows its tank tightly around a corner is easier for the opposing tank to reach than a backline offset from that corner.","mechanism","Corner swing and tank–backline trade","high","high","Requires visual review for geometry and example validity."),
 ("P4-010","z9n-JNB52rk",135,195,"composition/space","He frames many Overwatch 2 fights as tank–backline reach and trade problems and says a team may engage or bait that interaction; these are broad explanatory simplifications, not strict composition taxonomy.","framework","Overwatch 2; explicit broad simplification","high","medium","Potential tension with older brawl/dive/poke vocabulary, not a proved contradiction."),
 ("P4-011","z9n-JNB52rk",457,521,"space/positioning","A team going first around a corner can still plan to kite in the midfight; its backline needs an offset position and a window, such as an opponent's key cooldown being spent.","conditional_rule","Orisa mirror example","medium","high","Map and cooldown names in ASR are unreliable; inspect original video."),
 ("P4-012","pMPwEwNEiQA",115,178,"attention/player","After a successful Genji engage, the player should recheck enemy threats before chasing another kill; tunnel vision turns a favorable trade into a needless coin flip.","conditional_rule","Genji review","high","high","Specific fight result is the speaker's interpretation."),
 ("P4-013","pMPwEwNEiQA",490,535,"attention/player","For Genji, tracking who is looking at him and when pressure shifts matters more than merely minimizing damage taken.","mechanism","Illustrated Genji play","medium","high","Strong phrasing depends on replay scene; preserve as his heuristic."),
 ("P4-014","K6Ayz-NHVe4",90,165,"turns","He defines going first as choosing the engage and going second or baiting as allowing the opponent to commit before responding; hero and meta affect how those actions look.","definition","2024 analysis; his stated personal usage","high","low","Compare later refinements of first/second terminology."),
 ("P4-015","K6Ayz-NHVe4",400,460,"space/setup","An effective bait setup preserves the ability to punish an incoming engage; simply kiting without ever standing ground to punish it misses the purpose.","conditional_rule","Illustrated Korean team defense","high","high","Video needed to test whether the setup actually prevented the engage."),
 ("P4-016","MYW1ztAeDQc",55,115,"dive/setup","The expected outcome of a mirrored Winston–Tracer dive depends heavily on the quality of each dive's staging, rather than a fixed rule that the backline always lives or dies.","framework","Dive mirror hypothetical","high","medium","Speaker recognizes player skill and ultimates as additional factors."),
 ("P4-017","MYW1ztAeDQc",245,342,"dive/prevention","Against a well-staged dive, reviewing only defensive cooldown execution is often too late; instead, prevent the Tracer angle or Winston jump from becoming favorable before walking up.","conditional_rule","Ana–Brigitte retake example","high","high","The emphatic 'impossible to live' rhetoric is conditional on a genuinely good dive."),
 ("P4-018","MYW1ztAeDQc",600,700,"dive/retake","A wide retake route can clear or displace the dive setup, presenting the enemy Winston with a poor long-distance dive or a concession of space.","mechanism","Falcons retake example","medium","high","Requires map and POV review before elevating to a general rule."),
 ("P4-019","E1bYy6OE_OQ",45,99,"information/setup","Before a good setup, teammates should maximize safe sight of the enemy; he distinguishes broad team sight from scouting a specific player.","definition","2025 Geekay analysis","high","medium","His term 'sight maxing' is local vocabulary, not a validated metric."),
 ("P4-020","E1bYy6OE_OQ",120,200,"information/setup","Poking far forward between fights can reveal the enemy's walk-up, after which a team can withdraw behind a corner while retaining information and denying the same view to its opponent.","mechanism","Geekay versus Nightmare illustration","high","high","Visual inspection needed to verify visibility for each POV."),
 ("P4-021","LpxT2dykNK0",40,100,"staging/space","The pre-fight staging phase is a contest over how each team shapes the fight; conceding angles and retreating only after the enemy has finished setting up can lose before the nominal engage.","framework","Korean versus Western example","medium","high","Avoid turning regional rhetoric into a universal empirical claim."),
 ("P4-022","1OvQ5PAK0w0",30,80,"review/attention","Replay analysis should reconstruct what players could know and were prioritizing at the moment, rather than explain a death solely with hindsight.","method","2025 match review","high","medium","Ascribes possible mental states; verify through player POV where possible."),
 ("P4-023","1OvQ5PAK0w0",110,190,"review/attention","A postgame list of correct actions can be less useful than identifying the in-game attention process that prevented known actions from being executed under limited mental bandwidth.","method","Coaching and match review","high","low","Distinct from denying value of tactical knowledge."),
 ("P4-024","1UNctVbRS3M",25,90,"composition/setup","Low-damage double-flex DPS setups cannot rely as much on forcing tank cooldowns or long-range picks; they depend more on pathing, scouting, and avoiding head-on contests.","conditional_rule","Specific double-flex DPS composition discussion","medium","high","Patch and composition context must be checked before generalizing."),
 ("P4-025","1UNctVbRS3M",90,175,"cooldowns/tempo","A DPS may yield an angle to an opponent's clearing attempt, preserving own resources; the opponent's spent movement and subsequent retreat become a window to re-enter.","mechanism","Specific Genji/D.Va illustration","medium","high","Counterplay depends on exact paths and cooldown state."),
 ("P4-026","aHwWbiUE4KQ",0,95,"ultimate_economy","Ultimate economy still exists, but he argues it generally carries less explanatory weight in Overwatch 2 than in Overwatch 1; he explicitly exempts some D.Va, Zarya, and Symmetra compositions.","qualified_thesis","2026-01 analysis; composition and meta dependent","high","low","Title is deliberately stronger than the actual spoken claim."),
 ("P4-027","aHwWbiUE4KQ",100,250,"ultimate_economy","More individual playmaking, splits, and messy trades can let a team win despite spending or facing an apparent ultimate deficit.","mechanism","Overwatch 2 versus Overwatch 1 argument","medium","high","Match outcome examples have not been independently checked."),
 ("P4-028","aHwWbiUE4KQ",265,400,"ultimate_economy/space","Spacing the backline while a sturdier front line shows can draw an enemy ultimate and permit a kite, making the opponent's stored ultimate less decisive.","mechanism","Specific bait example; more mobile OW2 context","medium","high","Visual review required for the actual spacing and timing."),
 ("P4-029","aHwWbiUE4KQ",440,555,"ultimate_economy/objective","Winning a fight can generate later ultimate charge and next-fight setup; losing a fight creates a retake burden, so counting only ultimates spent omits these state changes.","mechanism","Meta dependent; his third reason","high","medium","Numerical charge examples should be checked visually."),
 ("P4-030","Hl-nV1aF1yE",55,160,"space/tempo","When a direct push through a prepared Sig/Bastion and Mei defense is unworkable, backing out early can hide a new route and create a later push opportunity.","conditional_rule","Specific map and composition situation","high","high","Do not generalize as retreating whenever pushing is hard."),
 ("P4-031","Hl-nV1aF1yE",190,310,"space/tempo","Early voluntary withdrawal while cooldowns and distance remain differs from backing up after poke has forced a retreat; the latter can allow pursuit and further loss of space.","distinction","Explicit response to possible tension with prior 'Lock Eyes and Fight' video","high","high","Speaker himself flags and reconciles the apparent contradiction."),
 ("P4-032","Hl-nV1aF1yE",345,405,"space/tempo","After spending an unsuccessful first turn, a team can retreat before the opponent closes, retain room to act, and regain the initiative for a later turn.","mechanism","Twisted Minds example","medium","high","Outcome and spacing need visual verification."),
 ("P4-033","KlcWDgdXrZk",0,98,"turns/vocabulary","First and second are useful descriptions of timing but poor instructions on their own; playing second requires flexible coverage of possible opponent decisions.","framework","2026 Falcons–Crazy Raccoon match","high","high","Refines the 2023–2024 vocabulary without rejecting it."),
 ("P4-034","KlcWDgdXrZk",135,365,"turns/opponent_model","A team seeking to play second may intentionally offer a cooldown trade or punishable position to induce a predictable opponent commitment, then arrange a counter-engage.","mechanism","Falcons examples","high","high","Speaker also shows this can fail; see P4-035."),
 ("P4-035","KlcWDgdXrZk",635,735,"turns/counterplay","The first-moving team can accept such bait if it responds quickly and coherently; a second-moving team that spends cooldowns to bait and then merely mirrors the same engage risks losing the cooldown trade.","counterexample","Falcons–Crazy Raccoon later fight","high","high","Prevents treating P4-034 as an always-win rule."),
 ("P4-036","GKkzCd9cvUg",110,180,"ultimate_economy","In the later follow-up he maintains that spending multiple support ultimates to win can be acceptable; the reviewed failure was spending them while losing and without a viable post-fight setup.","clarification","2026-04 follow-up to 2026-01 thesis","high","high","Explicitly distinguishes ult spending from failure to win a fight."),
 ("P4-037","GKkzCd9cvUg",230,350,"ultimate_economy/positioning","In the reviewed Zenyatta–Brigitte fight, he prefers a wide swing and kiting the opposing response rather than committing into it with both support ultimates.","case_judgment","Specific match, may depend on cooldown tracking","medium","high","He acknowledges uncertainty about exact ult tracking."),
 ("P4-038","GKkzCd9cvUg",390,475,"ultimate_economy/setup","A point flip is insufficient if the team clusters on point and lacks angles or a pinch for the next touch; the quality of the resulting setup matters more than the count of ultimates spent.","case_judgment","Specific post-ultimate retake","high","high","Visually validate positioning and outcome."),
 ("P4-039","KLwLiiYYewQ",0,51,"information/space","Poking past a choke before backing up can locate the opponent and preserve initiative; simply holding the choke can permit the enemy to arrange its own play.","conditional_rule","One short 2026 commentary clip","medium","high","Short clip; not enough context for a universal rule."),
 ("P4-040","_pv_dhja-4w",135,305,"learning/method","For players below the highest level, he recommends deliberate observation of real games over relying on first-principles mental simulation of an extremely complex game.","method","2026-09 learning advice; explicitly qualified for top experts","high","low","Rhetorical ranking advice, not a measured learning experiment."),
 ("P4-041","_pv_dhja-4w",310,555,"learning/method","He recommends writing a detailed record of a pro replay to expose unnoticed events and patterns, then comparing a closely matched own replay to identify differences.","method","Serious, time-intensive practice proposal","high","low","He admits the three-step scheme was improvised; do not invent a missing step."),
 ("P4-042","_pv_dhja-4w",620,690,"learning/evidence","When testing a tactical disagreement, seek several closely comparable real examples and check for confounds rather than relying only on hypothetical arguments.","method","Non-expert learning and team discussion","high","low","Consistent with P4-022 but a distinct claim about evidence."),
 ("P4-043","XXrcVGWBmo4",0,38,"support/peel","Brigitte should shield an allied Cassidy using Deadeye and counter-bash an enemy Rally attempt that would interrupt him.","conditional_rule","Specific Brigitte–Cassidy ultimate interaction","high","high","Short clip; corroborate exact interaction and positioning visually."),
 ("P4-044","nddeTxFzT6Q",45,112,"hitscan/role","Hitscan must pressure the enemy tank's advance while remaining difficult to trade; raw aim alone does not resolve the tension between damage and survival.","framework","Tank-focused neutral in the illustrated composition","medium","medium","Automatic captions are unusually garbled in this video; validate wording against audio."),
 ("P4-045","nddeTxFzT6Q",635,720,"hitscan/positioning","When a teammate forces a tank cooldown, the hitscan need not follow the frontline into reach; maintaining a safe firing angle can exploit the advantage without becoming the easiest trade.","conditional_rule","Illustrated Orisa cooldown exchange","medium","high","ASR and exact player names unreliable; verify visual example."),
 ("P4-046","V-Y0hBOI1yY",90,175,"tank/resource","In the then-current Mauga mirror, retaining armor changes the sustain versus incoming damage trade; engaging before armor is restored can make a tank suddenly punishable.","conditional_rule","2024 Mauga meta, with team healing available","medium","high","Patch dependent and rhetorical numerical claims are not independently measured."),
 ("P4-047","V-Y0hBOI1yY",530,625,"tank/tempo","A soft Mauga charge through an angle and back toward safety can create neutral pressure while preserving an exit, unlike committing the charge into the entire enemy team.","mechanism","Specific Mauga neutral and matchup","high","high","Exact route and punishability require video."),
 ("P4-048","V-Y0hBOI1yY",635,725,"tank/ultimate","A Mauga cage need not contain all five opponents; splitting frontline from support, or catching a reachable target without losing armor on entry, can be more valuable than an exposed five-person cage.","conditional_rule","Specific cage examples in 2024 meta","high","high","The fight outcome is the speaker's evaluation."),
 ("P4-049","XhcF5IzJDq4",200,365,"support/positioning","A Brigitte can walk in on a teammate's cooldown trigger and withdraw before taking damage, reducing exposure to the next enemy engage and preserving midfight options.","conditional_rule","2024 Mauga–Brigitte example","high","high","His 'unluckiness meter' is a metaphor for accumulating exposure, not a quantified probability."),
 ("P4-050","STbH6hH8emk",145,238,"echo/cooldowns","When the opposing Echo spends flight without gaining value, a saved flight can be used to threaten her or zone a Juno, changing which side can contribute to the frontline fight.","mechanism","Echo mirror in specified composition","high","high","Visual check needed to see whether flight was actually unpunishable and what was zoned."),
 ("P4-051","STbH6hH8emk",250,315,"echo/fight_plan","Echo's target choice follows the team's intended fight: help force frontline cooldowns in a front-to-back fight, or reach a genuinely exposed backline when the frontline contest cannot succeed on its own.","conditional_rule","2024 Mauga–Reaper–Echo match context","high","medium","Keep target-selection conditions; do not turn into universal hero advice."),
 ("P4-052","STbH6hH8emk",515,665,"echo/discipline","Preserving flight until the backline becomes reachable or the opposing Echo must make a play can protect a favored frontline fight; flying upward merely for extra poke can forfeit that option.","conditional_rule","Illustrated cage/Reaper ultimate fights","high","high","Requires visual verification and patch context."),
 ("P4-053","QvMsOy1wFr4",575,605,"ultimate_economy","When losing the retake would snowball into charge and objective disadvantage, spending two or even three ultimates to secure one fight can be justified.","conditional_rule","Specific NRG retake; not a blanket ratio","high","high","Important earlier evidence for the later qualified ult-economy thesis."),
 ("P4-054","QvMsOy1wFr4",730,795,"bait/pressure","If both teams wait to go second, the team without objective control must apply frontline pressure or create angles to force an opponent decision; a safely positioned backline alone does nothing.","conditional_rule","NRG example with objective pressure","high","high","Compare first/second definitions and specific fight geometry."),
 ("P4-055","QvMsOy1wFr4",1310,1390,"tempo/engage","A fast composition need not constantly move at maximum pace; it can delay, observe the opposing setup, and accelerate when the chosen trigger appears.","definition","Illustrated NRG engage","high","medium","His acceleration analogy is qualitative."),
 ("P4-056","p609brPyPzg",85,140,"hazard/micro","Hazard's wall climb can improve scouting and the angle for placing a wall behind an opponent before a slash engage.","mechanism","Newly released Hazard, 2024 example","high","high","Hero kit and patch dependent; verify wall geometry."),
 ("P4-057","p609brPyPzg",650,800,"hazard/fight_plan","In a mirrored Hazard backline trade, choose between stalling the enemy backline and reaching for a kill according to whether one's own team can survive and punish the opposing engage.","conditional_rule","Hazard mirror and team setup","high","high","Speaker presents contingent options rather than one fixed dive rule."),
 ("P4-058","GYBpp0KM5-Q",170,345,"draft/composition","Banning a support can force an opponent to choose between preserving a desired hero with a weaker support partner and changing the whole support line and composition playstyle.","mechanism","Early 2025 hero-ban context; named support pairings are patch specific","high","medium","His prediction that support bans dominate is a hypothesis, not a validated tournament result."),
 ("P4-059","GYBpp0KM5-Q",735,865,"support/dive","A Kiriko–Lucio backline should plan a teleport destination away from a second diver before the first diver forces the movement; teammates can position to provide that safe target.","conditional_rule","Hazard–Genji dive example","high","high","Path and second-diver position require replay confirmation."),
 ("P4-060","cXnFhS2l47g",85,165,"adaptation/setup","A strong setup can deny the other team's staging routes, leaving its own engage timing and micro as the second part of a simple fight plan.","case_judgment","Rad versus Nightmare early matchup","high","high","Narrator's reconstruction, not an independently verified match mechanism."),
 ("P4-061","cXnFhS2l47g",840,1015,"adaptation/spacing","Against a coordinated swing at Hazard, starting farther from the corner can force opponents to cross open space; if they instead rotate or split, Hazard regains an engage opportunity.","case_judgment","Nightmare rematch adaptation versus Liquid","high","high","Crucial example of changing the opponent's available options; map-dependent."),
 ("P4-062","vNp9kRvOjKA",180,420,"learning/effort","He argues that an ambitious player should practice at the standard of the next level before receiving its opportunity, while explicitly exempting those playing for enjoyment and conceding unusual constraints can exist.","coaching_thesis","Advice to competitive aspirants, not a gameplay law","high","low","Preserve the qualification from later in the passage and avoid treating career outcomes as measured facts."),
 ("P4-063","n-t2m7R_Gho",735,795,"dive/prevention","Allowing an opposing Winston multiple staging jumps without contesting him or changing the team's route can hand him a favorable dive setup.","case_judgment","Live Geekay–Liquid commentary","medium","high","Entertainment-heavy stream; do not extract his insults as evidence."),
 ("P4-064","GIY_4hD9_M8",2350,2465,"dive/setup","A tank's strong clearing jump creates only a short window; DPS must take a matching angle at that time rather than letting the opposing dive restage uncontested.","case_judgment","T1–Crazy Raccoon review, specific composition","medium","high","Live commentary; several proper names and hero terms are misrecognized."),
 ("P4-065","SJdCkYn6Is0",35,165,"tank/micro","The first dive target has defensive abilities to outplay; Winston can use bubble placement and timed movement to draw or dodge sleep and a boop before reaching for a kill.","mechanism","Donghak example, Ana–Brigitte backline","high","high","Timing and actual cooldown usage require enemy POV review."),
 ("P4-066","SJdCkYn6Is0",385,470,"tank/micro","Against another support pairing, the same general task of drawing defensive tools changes its implementation: a Ball engage may bait a boop or flash before slamming.","conditional_rule","Illustrated Ball versus Lucio–Kiriko–Cassidy","high","high","Different kit, same response-contingent mechanism; patch dependent."),
 ("P4-067","xabIcyolpJA",115,300,"dps/positioning","Leaving an angle before opponents force the exit buys more distance and time, allowing a burst DPS to reappear from another angle with fresh pick chances.","mechanism","Freja duel and rotation examples","high","high","Narrator's interpretation of repeated positions, visually unverified."),
 ("P4-068","xabIcyolpJA",295,350,"dps/target_choice","When a favored duel is unavailable, a DPS can still contribute frontline damage and cooldown pressure instead of forcing an unwinnable duel.","conditional_rule","Freja example","high","medium","Preserve the role's alternate job."),
 ("P4-069","x5ej22cA7G0",380,500,"learning/questions","A useful coaching question should show what the student has tried and isolate a specific obstacle, so the coach can answer the actual problem rather than first discovering it.","method","Coaching communication","high","low","Distinguish actionable advice from surrounding venting."),
 ("P4-070","vu4KmVKp2f0",35,115,"symmetra/teleport","Symmetra teleport can enable a direct brawl, an angle or angle clear, or a larger rotation; the defense must identify and reduce the valuable options before activation.","framework","2025 tournament matchups","high","high","The first half enumerates TP types; the example requires visual check."),
 ("P4-071","vu4KmVKp2f0",125,180,"symmetra/counterplay","Trying merely to survive a well-positioned teleport can already concede the fight's space and initiative; contest its setup or force a poorer teleport earlier.","case_judgment","Crazy Raccoon versus Twisted Minds","high","high","Specific match and composition, not universal TP outcome."),
 ("P4-072","vu4KmVKp2f0",390,540,"draft/counterplay","A counter composition must repeatedly deny or punish teleports across cooldown cycles; a dive that can only contest the first TP and then needs lengthy restaging may lose the continuing map fight.","mechanism","Ball–Venture–Freja versus Symmetra example","high","high","Cycle timing, map, and match outcome need visual audit."),
 ("P4-073","aNBstKtsPms",160,230,"hitscan/positioning","If a team chooses an early fight, the hitscan should already have an effective angle before the enemy engage reaches his preferred spot, rather than entering late beside the tank.","case_judgment","Reaction to another coach's Sojourn review","medium","high","Two speakers; this row paraphrases Capitology's added interpretation."),
 ("P4-074","aNBstKtsPms",295,390,"hitscan/positioning","Avoiding death by hiding too far away can make a hitscan unable to contest space; a useful retreat path should preserve a safe angle and future contribution.","qualified_rule","Sojourn versus dive example","medium","high","ASR rough, but the distinction is repeated clearly."),
 ("P4-075","ln2t2rl1KYw",80,180,"range/engage","He calls the opponent's effective reach the pocket: before entering it, a team should know what it will threaten, what can hit back, and how it will mitigate that response.","definition","Boxing analogy applied to Overwatch staging","high","medium","The pocket is contextual, not a fixed distance."),
 ("P4-076","ln2t2rl1KYw",620,770,"range/engage","Scouting and a forced enemy cooldown can justify entering the pocket with a planned response, while an unscouted five-person walk-in may spend resources before achieving useful positioning.","conditional_rule","Specific team review","high","high","Ultimates and composition can alter when brute force is viable."),
 ("P4-077","2X_yEWyNms0",105,200,"game_design/meta","He argues balance decisions should consider role-wide alternatives and composition effects, since nerfing one high-performing hero may miss why a whole role category dominates.","design_opinion","2025 patch commentary, not an observed strategic law","high","low","Patch-specific opinion; separate from tactical claims."),
 ("P4-078","LSrm0ocaS1Q",65,175,"aim/decision","He distinguishes anticipatory aim based on movement patterns from relying mainly on raw cursor correction; he presents anticipation as a more teachable route to consistent high-level hitscan duels.","framework","His theory-versus-raw-aim interpretation","medium","high","Inferred attention from replay, not measured cognition; he admits uncertainty about specific shots."),
 ("P4-079","LSrm0ocaS1Q",480,610,"aim/decision","In a duel, cutting off an ongoing strafe and waiting for a likely return strafe are alternative shot plans; overusing the wait can give a dangerous opponent free shots.","conditional_rule","Long-range Cassidy duel example","high","high","Requires frame-level confirmation for actual crosshair and movement."),
 ("P4-080","sqtmsbHxrLE",215,295,"meta/adaptation","He disputes the inference that a tournament-winning Symmetra lineup must be universally best; a match is a snapshot of team preparation, skill, and specific composition choices.","qualified_thesis","Late 2025 tournament retrospective","high","medium","His comparative team-skill judgment remains his opinion."),
 ("P4-081","AcAxvnAEYpg",720,850,"turns/window_size","A small opponent cooldown window may warrant taking an angle or some map space, not an all-in team engage; choosing who can use the window is as important as noticing it.","conditional_rule","D.Va flight example in team review","high","high","Relates to later 'first/second' refinement."),
 ("P4-082","Y4ORvoqZ1P0",230,335,"turns/roles","A frontline window can be exploited by distant backline support without the support stepping into engage range; misreading whose turn it is can sacrifice a favorable fight.","case_judgment","Specific late 2025 dive/teleport example","medium","high","ASR hero names unclear; visual review needed."),
 ("P4-083","M8393UkZxjY",840,985,"dps/timing","Taking an obvious high-value flank too early allows opponents to clear it; delaying that position until a fight begins can make the same angle harder to deny.","conditional_rule","Echo/Genji review against teleport composition","medium","high","ASR is partially garbled; compare with P4-067 and P4-084."),
 ("P4-084","jSCHyAWoUjc",285,365,"dps/timing","A burst DPS can start flexibly for scouting and route choice, then move quickly to the valuable flank after enemy movement reveals the fight, avoiding an early clear or bypass.","conditional_rule","Vendetta example; also references Echo play","high","high","Specific geometry and timing require replay."),
 ("P4-085","jSCHyAWoUjc",190,260,"dps/pressure","If opponents repeatedly space a threatened engage, taking the conceded space and delaying the engage can be better than forcing it; shooting the tank with teammates remains an option when angles are unnecessary.","conditional_rule","Vendetta neutral discussion","high","medium","Counters a simplistic always-flank reading."),
 ("P4-086","t1dnez3yuZ4",510,560,"ultimate_economy/timing","A team that plans to answer the opponent's ultimate with a nearly charged defensive ultimate may need to farm the final charge before committing its own entry.","case_judgment","Specific Lucio Beat and Graviton sequence","medium","high","Contextual counterexample to any slogan that ult economy never matters."),
 ("P4-087","TOaKp3Z44ho",35,112,"information/marking","In a Ball–Tracer–Sombra matchup, losing track of the enemy backline rotation while attending to another threat can let that group pass a defensive hold for free.","case_judgment","Entertainment-heavy live commentary","low","high","Provisional, rough ASR and rapid banter; watch before promotion."),
 ("P4-088","FjoWkH6Sl1k",675,780,"review/diagnosis","He separates a sensible split and setup from the later execution errors that lost an example fight, resisting a wholesale rejection of the initial plan after the result.","method","Tier-two live review","medium","high","Judgment of a single fight, needs visual audit."),
 ("P4-089","mXrTyliwJTI",0,60,"hitscan/patience","A hitscan can delay a shot and stay concealed to retain surprise until a better follow-up appears, rather than firing at the first visible target.","case_judgment","One-minute reaction clip","low","high","Context missing; do not generalize without footage."),
 ("P4-090","AtmKIdmLLQ8",495,570,"review/hindsight","A roster or draft decision should be evaluated using information available before the match, rather than its observed outcome alone.","method","Roster selection commentary","high","low","Distinct from actual claim that any specific roster choice was correct."),
 ("P4-091","ijlmDdVIdtk",70,155,"composition/aggro_balance","He frames a contemporary Winston double-flex composition as multiple splits balancing attention: the pressured split yields, the others press, and high-level fights may repeat this exchange over several turns.","framework","2026 team-composition analysis","high","high","Terminology and composition are era dependent; compare 2023 split-core account."),
 ("P4-092","ijlmDdVIdtk",770,900,"bait/counterplay","Offering a punishable teammate can steer an opponent's decision but may cost a death; teams can adapt by declining the bait and conceding some space, with different subsequent risks.","case_judgment","Dallas Fuel–SSG review","medium","high","He explicitly leaves which style is better unresolved."),
 ("P4-093","prUv2eNrGD0",1020,1205,"hitscan/development","Across a small matched-map Sojourn sample, he observes progression in pre-fight poke, changing angles, scouting rotations, farming rail, and looking quickly for picks; the comparison is illustrative, not a controlled rank study.","observational_pattern","Five selected players from Diamond to pro","high","high","Guest speech is present; this row paraphrases the narrator's comparisons."),
 ("P4-094","prUv2eNrGD0",1460,1550,"hitscan/decision","The pro player describes farming rail from the tank and quickly scanning for exposed targets; the narrator highlights the speed of that transition as a higher-level distinction.","observational_pattern","Sojourn pro interview; narrator interpretation plus guest report","medium","high","Preserve speaker attribution; check footage for each alleged opportunity."),
 ("P4-095","N5fHwbNE-SQ",245,330,"bait/space","In a slow defensive style, the front line must actively delay an enemy walk-up while the backline keeps useful angles; standing very far back without contesting the path is insufficient.","conditional_rule","Cjay interview; speaker attribution needs audio check","low","high","Auto captions are heavily corrupted in this upload; do not promote without audio."),
 ("P4-096","iLX7uqsC1jE",750,780,"mechanics/close_fights","He cautions that mechanical differences and missed shots can decide otherwise sound fight plans, especially when a close match has small margins.","qualified_thesis","Q&A; illustrative estimate, not a measured 5% effect","high","low","Avoid a false dichotomy between mechanics and strategic understanding."),
 ("P4-097","iLX7uqsC1jE",1110,1145,"learning/attention","For a player unsure of their job, he advises writing a short list of possible duties and practicing one or two at a time to preserve awareness and flexibility.","method","Q&A advice","high","low","Specific three-to-four-item list suggested in speech."),
 ("P4-098","iLX7uqsC1jE",1180,1260,"learning/practice","Knowing a principle in theory is different from executing it; repeated practice of small, specific actions is needed to close that gap.","method","Q&A response to player frustration","high","low","The hundreds/thousands language is rhetorical, not a calibrated repetition count."),
 ("P4-099","x2jNJeKiMUU",985,1065,"game_design/counterplay","In a pre-release hero reaction, he worries that complete invulnerability on a flanker could remove too much opponent counterplay, while also valuing a flanker able to poke and later threaten the backline.","design_opinion","Speculative first impression of announced hero kit","medium","high","Do not treat predicted balance or kit behavior as a tested strategic fact."),
]

# Source was checked but a stable strategic proposition was not recoverable.
# The Shorts were read in full; the announcement concerns content plans.
NO_MODEL_CLAIM = {
    "GjlM3r948EI": "23-second reaction; visual event cannot be inferred from the caption alone",
    "pQcjwEjo6us": "31-second banter with an incomplete turn reference; context too thin",
    "UC8D2vBDf_0": "Channel schedule and Patreon announcement, not an Overwatch tactical lesson",
}

def clock(seconds):
    return f"{seconds//3600:02d}:{seconds//60%60:02d}:{seconds%60:02d}"

def main():
    seen = set()
    rows = []
    for id_, video_id, start, end, topic, claim, claim_class, scope, confidence, visual, note in CLAIMS:
        assert id_ not in seen and start < end
        seen.add(id_)
        meta = VIDEO[video_id]
        rows.append(dict(claim_id=id_, video_id=video_id, video_title=meta["title"], upload_date=meta["upload_date"], start=clock(start), end=clock(end), start_seconds=start, end_seconds=end, url=f"https://www.youtube.com/watch?v={video_id}&t={start}s", topic=topic, claim=claim, claim_class=claim_class, scope=scope, evidence_type="automatic_caption_speaker_paraphrase", transcript_confidence=confidence, visual_dependency=visual, review_note=note, gameplay_verified=False, status="provisional"))
    with (ROOT / "pass04_claims.jsonl").open("w") as f:
        for row in rows: f.write(json.dumps(row,ensure_ascii=False)+"\n")
    with (ROOT / "pass04_claims.csv").open("w",newline="") as f:
        w=csv.DictWriter(f,fieldnames=rows[0].keys()); w.writeheader();w.writerows(rows)
    video_index=json.load((ROOT / "pass03_video_index.json").open())["videos"]
    counts={v:sum(r["video_id"]==v for r in rows) for v in VIDEO}
    assert {v["video_id"] for v in video_index}=={v for v,n in counts.items() if n} | set(NO_MODEL_CLAIM)
    with (ROOT / "pass04_coverage_queue.csv").open("w",newline="") as f:
        w=csv.writer(f);w.writerow(["video_id","title","upload_date","duration_seconds","pass03_segments","pass04_status","provisional_claims","topic_tags","pass03_relevance","pass03_visual_priority","note"])
        for v in sorted(video_index,key=lambda x:x["upload_date"]):
            vid=v["video_id"];n=counts[vid]
            status="sampled_not_exhaustive" if n else "reviewed_no_model_claim"
            note="Transcript windows sampled; remaining windows and video footage pending" if n else NO_MODEL_CLAIM[vid]
            w.writerow([vid,v["title"],v["upload_date"],v["duration_seconds"],v["segment_count"],status,n,";".join(x[0] for x in v["primary_topics"]),v["average_strategic_relevance"],v["average_visual_review_priority"],note])
    print(f"Wrote {len(rows)} claims from {len({r['video_id'] for r in rows})} videos; {len(NO_MODEL_CLAIM)} reviewed without model claims")

if __name__ == "__main__": main()
